PROJECT_NAME: Medpoint-Backend
PROJECT_ID: qfpmcwbrucsukmjudugu
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_1af9329c395899f1ff1fad90588944eb58d323d8
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmcG1jd2JydWNzdWttanVkdWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4NTk2NzIsImV4cCI6MjA0ODQzNTY3Mn0.XiU3NC3PjiJHUsG5HCpsVxChmIPNnDS4540mA6MJkFQ
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmcG1jd2JydWNzdWttanVkdWd1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMjg1OTY3MiwiZXhwIjoyMDQ4NDM1NjcyfQ.ronpz2RoMkQnH9SLxuZ-Bmz74iP3UnsyEU03vsww5Vs

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://qfpmcwbrucsukmjudugu.supabase.co

SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
